//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDV.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TDV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} -&gt; {1} to {2} - {3}.
        /// </summary>
        internal static string MainWindowsVM_DisplayFileSystemWatcherInfo_DateOldFileNameToNewName {
            get {
                return ResourceManager.GetString("MainWindowsVM_DisplayFileSystemWatcherInfo_DateOldFileNameToNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro security not detected {0}.
        /// </summary>
        internal static string MainWindowsVM_SetExcelSecuritySettings_MacroSecurityNotDetected {
            get {
                return ResourceManager.GetString("MainWindowsVM_SetExcelSecuritySettings_MacroSecurityNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro security : OFF.
        /// </summary>
        internal static string MainWindowsVM_SetExcelSecuritySettings_MacroSecurityOFF {
            get {
                return ResourceManager.GetString("MainWindowsVM_SetExcelSecuritySettings_MacroSecurityOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro security : ON.
        /// </summary>
        internal static string MainWindowsVM_SetExcelSecuritySettings_MacroSecurityON {
            get {
                return ResourceManager.GetString("MainWindowsVM_SetExcelSecuritySettings_MacroSecurityON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel version : {0}.
        /// </summary>
        internal static string MainWindowsVM_SetOfficeVersion_ExcelVersion {
            get {
                return ResourceManager.GetString("MainWindowsVM_SetOfficeVersion_ExcelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel dectection settings : KO.
        /// </summary>
        internal static string MainWindowsVM_SetSettings_ExcelDectectionSettingsKO {
            get {
                return ResourceManager.GetString("MainWindowsVM_SetSettings_ExcelDectectionSettingsKO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel dectection settings : OK.
        /// </summary>
        internal static string MainWindowsVM_SetSettings_ExcelDectectionSettingsOK {
            get {
                return ResourceManager.GetString("MainWindowsVM_SetSettings_ExcelDectectionSettingsOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start FileSystem Watcher &apos;{0}&apos;.
        /// </summary>
        internal static string MainWindowsVM_StartFileSystemWatcher_StartFileSystemWatcher {
            get {
                return ResourceManager.GetString("MainWindowsVM_StartFileSystemWatcher_StartFileSystemWatcher", resourceCulture);
            }
        }
    }
}
